### ISSUE TITLE
Timeout occured - where is the timeout setting

### ISSUE THREAD

**Issue by WolfgangFahl** [jneilliii/OctoPrint-BedLevelVisualizer#135]
I get "Bed Visualizer Error - Timeout occured before processing completed. Processing may still be running or there may be a configuration error. Consider increasing the timeout value in settings." 
![grafik](https://user-images.githubusercontent.com/1336221/59656477-fa7e8780-919d-11e9-87cb-3b271fc3eaf8.png)
while the G29 T command is still in progress.

The default timeout of 60 secs seems to be pretty low.

The message disappears so quickly that I couldn't read it. 

There is a typo in the message - it should be "processing"

**Comment by jneilliii** [comment]
Thanks for the call out on the typo. The timeout is there for instances when the process just never finishes and allow the interface to recover from processing. It's set at 60 seconds because the bed report can be retrieved without running a full probe process for some firmware/leveling types. For example you can use `M420 V` in marlin and just report the points.

**Comment by nickm324** [comment]
Same issue, is this being looked into? Is the time out configurable in some way?

**Comment by jneilliii** [comment]
Timeout is configurable in the plugin's settings.

**Comment by WolfgangFahl** [comment]
The message disappears so quickly that it is not obvious. People start searching the internet and end up here.
