### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Andy-Prusa** [jneilliii/OctoPrint-BedLevelVisualizer#293]
[192.168.0.3%2Fdownloads%2Flogs%2Fplugin_bedlevelvisualizer_debug.log.pdf](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/5192210/192.168.0.3.2Fdownloads.2Flogs.2Fplugin_bedlevelvisualizer_debug.log.pdf)
**Describe the bug**
When I run bed visualiser the output appears to hold no relation to the print test outcomes. E.g. where visualiser shows the bed farthest away is where the test print is squashed and rough. See attached image, front right is low but is squished, middle is higher, but prints too far away

**Expected behavior**
Bed visualiser output would reflect what I find in printing

**Debug Log**

Done

**Firmware and Version**

?latest

[
![EFE09B01-CFA8-4E6B-AC3F-4D80D3CD1AA1](https://user-images.githubusercontent.com/64402311/92546042-26df6180-f284-11ea-9b63-312e72f7b0b0.jpeg)
[192.168.0.3%2Fdownloads%2Flogs%2Fplugin_bedlevelvisualizer_debug.log(1).pdf](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/5192205/192.168.0.3.2Fdownloads.2Flogs.2Fplugin_bedlevelvisualizer_debug.log.1.pdf)
![C3C4A24A-4874-4EC1-BB9B-1583520117EA](https://user-images.githubusercontent.com/64402311/92546205-9a816e80-f284-11ea-9a7a-8d64bd3cd8c0.jpeg)

](url)

**Comment by jneilliii** [comment]
This is what the flip and rotate options are for in the plugin's settings. If for some reason the output is unexpected relative to the orientation of your bed's axis you have to kind of play with those until it's right. In your case I think you would flip both x and y, or potentially just rotate by 180 degrees.

**Comment by Lumute** [comment]
I'm using an Ender 5 Pro which has 0,0 at the Front-Left. I wanted to rotate the graph 60 degrees so its more intuitive but these settings in the general tab do not seem to be doing anything. I didn't start a new issue because maybe I'm not understanding the concept? or maybe I don't know how to make the new settings apply? or is it necessary to update the mesh again to get the graph to show using the new settings?

I tried saving the settings and hitting Ctrl+F5 and the graph shows exactly the same, I even tried restarting Octoprint + Ctrl+F5 and same. Also tried other settings like flipping x and y axis and nothing I don't see any difference in the graph... 

Everything I try it always displays the graph with 0,0 in the front like images above...

**Comment by jneilliii** [comment]
Those settings effect how the data is interpreted during the update mesh process. Only a couple of the settings will directly effect the graph without updating the mesh using the button.

**Comment by jneilliii** [comment]
Oh, and the graph itself will always begin its rendering with 0,0 facing you directly.

**Comment by Lumute** [comment]
Ah, yes I completely misunderstood the concept... so I guess the idea then is to use those options so that the coordinates the plugin assigns to each measurement received match the actual coordinates where the measurements were taken, correct?

Any idea how to practically figure that out? I guess I could put something on top of the bed on one of the corners and update the mesh to see which one has a very high value and flip until correct, or is there a better way?

**Comment by Andy-Prusa** [comment]
So I rotated mine 90 degrees after checking by doing what you said, ie put a piece of paper under one corner. The issue I still have is where it says it is too low it’s actually too high. Not sure what to do with this?

**Comment by Lumute** [comment]
Not sure if this is the same problem you are having but I had a similar issue because on my printer (Ender 5 Pro) Z axis is reversed (0 at the top and goes to 300 as the bed goes down).

So in my case, the graph is reversed (positive values up, negative down as any standard graph) and I have to do the opposite to what the graph shows, not very intuitive... I think the solution for this would be some separate settings that would control the way the graph is rendered so once you have your coordinates matching correctly you could flip the graph axis.

**Comment by jneilliii** [comment]
As I replied in the other FR, copying here for the benefit of others...there's this little move nozzle button that allows you to enable that option and then click on a point on the surface graph and the nozzle will move to that position. Which can assist on figure out what flip and rotate options are necessary to get your graph aligned with the real world layout of your bed.

![image](https://user-images.githubusercontent.com/5249455/94385917-498ec880-0114-11eb-8f32-da888d889937.png)

I'm still curious if this is related to core x/y motion versus other cartesian style movement. My assumption still is that if you slice a gcode file and look in it with a text editor it's not moving the z axis in the negative direction, it's still sends it as positive, but please let me know if that's not the case.

**Comment by Lumute** [comment]
Indeed, moving the nozzle with the graph is quite useful to figure out what is what, still, the trick with a prop in one corner helps confirm in case an axis is interpreted wrong and needs to be flipped.

About the Z axis, in the Ender 5 as you print the Z increases in the positive direction (because the bed goes down) but it is possible to go a little bit to the negative direction before you crash into the nozzle, that is mainly useful to level and calculate the Z Offset.
