### ISSUE TITLE
[FR]: Supporting more then 4x4 probing grid

### ISSUE THREAD

**Issue by theboy0007** [jneilliii/OctoPrint-BedLevelVisualizer#370]
Is it possible to make the plugin support more then 4x4 grid probing? I am running a 10x10 grid probing on my ender 5 but if i want to use the plugin to visualize this, the serial connection from octoprint to my printer disconnects.

**Comment by jneilliii** [comment]
Have you considered increasing your timeouts in OctoPrint and/or verified that your G29 command is in the Long Running Command section of Firmware & protocol > Advanced Options? 

![image](https://user-images.githubusercontent.com/5249455/106188116-8deaad80-6174-11eb-9f12-3462fddf680f.png)

I can't control what OctoPrint does relative to timeout and the plugin supports as many points that can be reported by the firmware. Depending on what type of leveling you are using you could potentially utilize the stored EEPROM mesh data instead by using the `M420 V` command instead of a full G29 probing, then do the probe outside of OctoPrint.

**Comment by KenLucke** [comment]
You can also speed up the probe itself, which may help, by specifying a speed.  I use 
G29 T S65000

BTW, I do 9x9 with no problems.
