### ISSUE TITLE
[FR]: Z Stepper Auto Alignment

### ISSUE THREAD

**Issue by Pheelix** [jneilliii/OctoPrint-BedLevelVisualizer#447]
Feature Request:

I know we can make custom command buttons.  But is there any chance you could add a  Z Stepper Auto Alignment button that works like the update button.  Or a way to have custom commands show the webcam when they run?  I do have the Auto Alignment command in the Bed Leveling commands but sometimes it is nice to run it by itself.

**Comment by jneilliii** [comment]
I could definitely add an option for the webcam to be visible while a custom button is pressed but not sure how to account for turning the webcam back off. Rather than applying it to the button though I think it might be better to apply it as an echo command, which would allow the printer to tell the plugin to enable/disable webcam. That way you could use something like the below in a custom command and achieve the end goal, assuming your firmware supports echo commands.

```
M118 BLVWEBCAMON
G34
M118 BLWEBCAMOFF
```
