### ISSUE TITLE
[FR]: Option to display height instead of angles on main screen.

### ISSUE THREAD

**Issue by ceshop-nick** [jneilliii/OctoPrint-BedLevelVisualizer#496]
Option to display mesh data height instead of only angles on main screen.

Display Mesh Data on tab screen with checkbox same as angle correction.  Then user could have both if they wanted.

**Comment by jneilliii** [comment]
Nice idea. I never thought to do that since you can hover your mouse over the points on the graph and it shows the height. I can see now seeing all the numbers can be helpful in some situations, like on your phone.

**Comment by jneilliii** [comment]
Need to work out the math changes needed on the adjustment area, as that doesn't seem to showing any numbers. It may take a while for me to figure that out though because I didn't create this part of the plugin and it will take me a while to understand how the contributor did what they did. 

![image](https://user-images.githubusercontent.com/5249455/147842363-32c501b0-15d0-4316-a539-212520d149f3.png)

**Comment by ceshop-nick** [comment]
Thank you for being so proactive on this on New Years eve(n).  What if you just copied the code to display on the main page from the angles to the Mesh Data page since that is already displaying the mesh data in mm already?  Then you could potentially have 3 sections on the page - Graph, Angles View, Mesh Data view - (up to the user to display all three or not).

**Comment by jneilliii** [comment]
That is actually a screenshot of the tab, just below the graph, so all three items can be enabled and shown on the tab all at the same time if configured that way.
