### ISSUE TITLE
[BUG]: Creality CR-10s w/Marlin 2.1.2 and BedLevelVisualizer v/1.1.2rc5

### ISSUE THREAD

**Issue by Icegames-dk** [jneilliii/OctoPrint-BedLevelVisualizer#614]
**Describe the bug**
BLV stops in the middel of the bed, with no errors.

**Debug Log**
[plugin_bedlevelvisualizer_debug.log](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/11440842/plugin_bedlevelvisualizer_debug.log)

**Screenshots**
![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/63652094/6619ee4e-65af-452e-82aa-467597a6eb38)
![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/63652094/880a932b-5404-482e-a1a5-76dde0b42aab)

**Firmware and Version**
Creality CR-10s w/Marlin 2.1.2 and BedLevelVisualizer v/1.1.2rc5

**Comment by jneilliii** [comment]
Not sure I understand what the issue is. Does it not generate a graph? The debug log seems to indicate that it does receive a proper mesh. One thing I notice is that you are using UBL commands, is that something you enabled in your own custom compile of Marlin or are you using a Creality provided firmware or other pre-built fork? It's fairly uncommon for manufacturers to use UBL and they typically enable bilinear instead.

**Comment by Icegames-dk** [comment]
Hi
It's the standard firmware from Marlin I used.
https://marlinfw.org/meta/download/

And this is the configuration files that they provide for Creality CR10s
[Creality CR10s.zip](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/11449675/Creality.CR10s.zip)


Please bear with me I am new to Octoprint :-)

**Comment by jneilliii** [comment]
It's what I was suspecting. Your marlin config is using bilinear. Change the gcode in the plugin's settings to that specific type, as documented [here](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/blob/rc/wiki/gcode-examples.md#bilinear-bed-levelling).
