### ISSUE TITLE
X/Y coordinates are not correct for delta printer with circular probing pattern  

### ISSUE THREAD

**Issue by Knas99** [jneilliii/OctoPrint-BedLevelVisualizer#73]
It seems that the X/Y coordinates used for plotting the bed level, are estimated from the bed size from Octoprint-setup and assumed to always be in a square pattern. 

Would be an option to manually add coordinates for X and Y? Then it would be possible to use a custom probing pattern...

**Comment by jneilliii** [comment]
There was a lot of work done to even get the circular bed stuff to work at all.  I wasn't made aware that there was an option for custom probing patterns.  In order to do anything with this I need to understand how your firmware reports it's bed leveling data?  For example, you may probe multiple points, but the report may return it as a standard cartesian grid?  When you run the report what is returned in terminal?
